### ISSUE TITLE
Unpublish feature 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#437]
**Description**
- Can user unpublish what s/he published? If it is the case we need an endpoint for that and also a variable like "ispublished"

**Comment by veyisTurgut** [comment]
There are some issues about that on my mind. I was planning to make things clear at lab session. @Refref18

**Comment by veyisTurgut** [comment]
This is what I'm gonna do:
- Add an isPublished field to the goal model. So that a goal will not be published more than once.
- Change publish a goal endpoint so that it will delete the corresponding prototype and republish the current status of the goal.
- Write unpublish endpoint which removes the corresponding prototype but keeps download count same.

**Comment by veyisTurgut** [comment]
Implemented in #466 @Refref18 Please read the pr description
